server:
  port: 0

# Registering order-service in Eureka Server as Client
eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka

# Zipkin configurations
management:
  tracing:
    sampling:
      probability: 1.0

# Kafka Consumer configurations
spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notify
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      properties:
#        spring.json.type.mapping: event:com.example.notificationservice.events.OrderPlacedEvent
        spring:
          json:
            value:
              default:
                type: 'com.example.notificationservice.events.OrderPlacedEvent'
            type:
              mapping: 'com.example.orderservice.events.OrderPlacedEvent:com.example.notificationservice.events.OrderPlacedEvent'
            trusted:
              packages: 'com.example.orderservice.events.OrderPlacedEvent'

  application:
    name: notification-service