# Registering API Gateway in Eureka Server
eureka:
  client:
    service-url:
      # registering api-gateway in Eureka Server as Client
      defaultZone: http://eureka:password@localhost:8761/eureka


# Routing requests to microservices
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
        routes:
          - id: product-service
            uri: lb://product-service
            predicates:
              - Path=/api/v1/product/**

          - id: order-service
            uri: lb://order-service
            predicates:
              - Path=/api/v1/order/**

          - id: discovery-service
            uri: http://localhost:8761
            predicates:
              - Path=/eureka/web
            filters:
              - SetPath=/

          - id: discovery-service-eureka
            uri: http://localhost:8761
            predicates:
              - Path=/eureka/**

          - id: path_route
            uri: https://kun.uz
            predicates:
              - Path=/red/{segment},/blue/{segment}
            filters:
              - SetPath=/en

# Securing Microservice with KeyCloak Server
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/realms/spring-boot-microservices-realm

# Zipkin configurations
management:
  tracing:
    sampling:
      probability: 1.0

# Logging
logging:
  level:
    org:
      springframework:
        cloud:
          gateway: trace
          gateway.route.RouteDefinitionLocator: info
    root: info
