spring:
  application:
    name: product-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/product-service

server:
  port: 8082

eureka:
  client:
    #    register-with-eureka: false
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka