# Connecting to MongoDB database
spring:
  application:
    name: product-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/product-service

server:
  port: 8082

# Registering product-service in Eureka Server as Client
eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka