# running inventory-service on random ports to run multiple instances of inventory-service to load balance
server:
  port: 0

# Database connection configurations
spring:
  application:
    name: inventory-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/microservices-project
    username: postgres
    password: root123
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default_schema: inventory_service
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl

# Registering inventory-service in Eureka Server as Client
eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka